// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvetKSx-lIuPMkNyUzTTeFmdDd1rsC7g',
    appId: '1:906244719920:web:eca3119731812388ed34f5',
    messagingSenderId: '906244719920',
    projectId: 'firebase-login-auth-app',
    authDomain: 'fir-login-auth-app.firebaseapp.com',
    storageBucket: 'firebase-login-auth-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0lAp9KwIHFdHuox33Nylt1JCdpC8RSI',
    appId: '1:906244719920:android:7120809f1c15acbded34f5',
    messagingSenderId: '906244719920',
    projectId: 'firebase-login-auth-app',
    storageBucket: 'firebase-login-auth-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBh-sAinw4eRXrRjYPNq58-amwjZahqVE',
    appId: '1:906244719920:ios:36107c8fa952d756ed34f5',
    messagingSenderId: '906244719920',
    projectId: 'firebase-login-auth-app',
    storageBucket: 'firebase-login-auth-app.appspot.com',
    iosClientId: '906244719920-nae3uus63tq7qpuoooa5qklnhnm0v1ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginAuthExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBh-sAinw4eRXrRjYPNq58-amwjZahqVE',
    appId: '1:906244719920:ios:36107c8fa952d756ed34f5',
    messagingSenderId: '906244719920',
    projectId: 'firebase-login-auth-app',
    storageBucket: 'firebase-login-auth-app.appspot.com',
    iosClientId: '906244719920-nae3uus63tq7qpuoooa5qklnhnm0v1ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginAuthExample',
  );
}
