// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnf1NKm30BtxnpkKskdLtM2lKKzLqiAhA',
    appId: '1:541557870982:web:090c3c07d3199dc6d15c07',
    messagingSenderId: '541557870982',
    projectId: 'super-simple-firebase-example',
    authDomain: 'super-simple-firebase-example.firebaseapp.com',
    storageBucket: 'super-simple-firebase-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO_bTaj6vWCVW3Jh72l04DglAZ-EmVKxY',
    appId: '1:541557870982:android:d3ecb3f32ac9eba3d15c07',
    messagingSenderId: '541557870982',
    projectId: 'super-simple-firebase-example',
    storageBucket: 'super-simple-firebase-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDur4_V-QVHWWPxioielAN7oLzmi_WXEps',
    appId: '1:541557870982:ios:7a77c011d9a3744fd15c07',
    messagingSenderId: '541557870982',
    projectId: 'super-simple-firebase-example',
    storageBucket: 'super-simple-firebase-example.appspot.com',
    iosClientId:
        '541557870982-jeka5pbspg9rrbbhm6pu6pphkt02to05.apps.googleusercontent.com',
    iosBundleId: 'com.example.superSimpleFirebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDur4_V-QVHWWPxioielAN7oLzmi_WXEps',
    appId: '1:541557870982:ios:7a77c011d9a3744fd15c07',
    messagingSenderId: '541557870982',
    projectId: 'super-simple-firebase-example',
    storageBucket: 'super-simple-firebase-example.appspot.com',
    iosClientId:
        '541557870982-jeka5pbspg9rrbbhm6pu6pphkt02to05.apps.googleusercontent.com',
    iosBundleId: 'com.example.superSimpleFirebaseExample',
  );
}
