// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkfSZffZrf-x0_6Be0a86kbEcJqoLA8Xo',
    appId: '1:1076905823126:web:8c2dc7873079b158c1abb7',
    messagingSenderId: '1076905823126',
    projectId: 'my-tiktok-flashcard',
    authDomain: 'my-tiktok-flashcard.firebaseapp.com',
    storageBucket: 'my-tiktok-flashcard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFOrxgumpp4T5j5qTaYIslxWUKOHzrztc',
    appId: '1:1076905823126:android:280b24bdb9a7ed5bc1abb7',
    messagingSenderId: '1076905823126',
    projectId: 'my-tiktok-flashcard',
    storageBucket: 'my-tiktok-flashcard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiPNGey5qQCwCYgOggk5Gxc_XhivX_h3s',
    appId: '1:1076905823126:ios:033e3c10cf7ce6c1c1abb7',
    messagingSenderId: '1076905823126',
    projectId: 'my-tiktok-flashcard',
    storageBucket: 'my-tiktok-flashcard.appspot.com',
    iosClientId:
        '1076905823126-33v7bo8drllkpvejt1cmf6m23ira9r19.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiPNGey5qQCwCYgOggk5Gxc_XhivX_h3s',
    appId: '1:1076905823126:ios:033e3c10cf7ce6c1c1abb7',
    messagingSenderId: '1076905823126',
    projectId: 'my-tiktok-flashcard',
    storageBucket: 'my-tiktok-flashcard.appspot.com',
    iosClientId:
        '1076905823126-33v7bo8drllkpvejt1cmf6m23ira9r19.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcard',
  );
}
